# Generated by Django 5.1.7 on 2025-06-03 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('issue_date', models.DateField(verbose_name='Issue Date')),
                ('state', models.IntegerField(choices=[(1, 'PROCESO'), (2, 'RECHAZADO'), (3, 'ACEPTADO')], verbose_name='State')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer', verbose_name='Customer')),
            ],
        ),
    ]
