# Generated by Django 5.1.7 on 2025-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Option', '0001_initial'),
        ('Quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='options',
            field=models.ManyToManyField(blank=True, to='Option.option', verbose_name='Options'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='tasks',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Tasks'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='state',
            field=models.IntegerField(choices=[(1, 'PROCESO'), (2, 'APROBADO'), (3, 'RECHAZADO')], verbose_name='State'),
        ),
    ]
