# Generated by Django 5.1.7 on 2025-06-13 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Option', '0001_initial'),
        ('Quotes', '0002_quotes_options_quotes_tasks_alter_quotes_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='administration',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Administration'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.19, max_digits=10, null=True, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='revision',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Revision'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='unforeseen',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Unforeseen'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='utility',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Utility'),
        ),
        migrations.RemoveField(
            model_name='quotes',
            name='options',
        ),
        migrations.AddField(
            model_name='quotes',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Option.option', verbose_name='Options'),
        ),
    ]
