# Generated by Django 5.1.7 on 2025-06-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0003_quotes_administration_quotes_iva_quotes_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='construction',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Construction'),
        ),
    ]
