# Generated by Django 5.1.7 on 2025-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0004_quotes_construction'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='administration_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Administration Value'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='iva_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='IVA Value'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='unforeseen_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Unforeseen Value'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='utility_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Utility Value'),
        ),
    ]
