# Generated by Django 5.1.7 on 2025-06-16 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0005_quotes_administration_value_quotes_iva_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='method_of_payment',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Method of Payment'),
        ),
    ]
