# Generated by Django 5.1.7 on 2025-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0006_quotes_method_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='construction',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Construction'),
        ),
    ]
