# Generated by Django 5.1.7 on 2025-06-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0007_alter_quotes_construction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='iva_value',
        ),
    ]
