# Generated by Django 5.1.7 on 2025-07-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0009_remove_quotes_administration_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='contracting_materials',
            field=models.JSONField(blank=True, null=True, verbose_name='contracting_materials'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='contractor_materials',
            field=models.JSONField(blank=True, null=True, verbose_name='contractor_materials'),
        ),
        migrations.AddField(
            model_name='quotes',
            name='delivery_time',
            field=models.CharField(blank=True, default='36 días hábiles', max_length=200, null=True, verbose_name='delivery_time'),
        ),
    ]
