# Generated by Django 5.1.7 on 2025-07-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes', '0010_quotes_contracting_materials_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='delivery_time',
            field=models.CharField(blank=True, default='36 días hábiles', max_length=200, verbose_name='delivery_time'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='method_of_payment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Method of Payment'),
        ),
    ]
