# Generated by Django 5.1.7 on 2025-04-04 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=700)),
                ('place', models.CharField(max_length=600)),
                ('entry_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('state', models.IntegerField(choices=[(1, 'Aceptado'), (2, 'Rechazado'), (3, 'En Espera'), (4, 'Finalizado')], default=3)),
                ('applicant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_as_applicant', to='users.users')),
                ('receiver', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_as_receiver', to='users.users')),
                ('tools', models.ManyToManyField(to='tool.tool')),
            ],
        ),
    ]
