# Generated by Django 5.1.7 on 2025-04-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
