# Generated by Django 5.1.7 on 2025-06-29 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='responsible',
            field=models.CharField(default='AFH', max_length=200),
        ),
    ]
