# Generated by Django 5.1.7 on 2025-04-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_departure_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='departure_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='entry_date',
            field=models.DateTimeField(),
        ),
    ]
