# Generated by Django 5.1.7 on 2025-04-06 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_departure_date_alter_ticket_entry_date'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='applicant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_as_applicant', to='users.users'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_receiver', to='users.users'),
        ),
    ]
