# Generated by Django 5.1.7 on 2025-07-24 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WorkAdvance', '0001_initial'),
        ('WorkOrder', '0006_remove_workorder_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[(1, 'Pendiente'), (2, 'En Progreso'), (3, 'Finalizado')], default=1, max_length=50)),
                ('work_advance', models.ManyToManyField(blank=True, to='WorkAdvance.workadvance', verbose_name='Work Advances')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrder.workorder', verbose_name='Work Order')),
            ],
        ),
    ]
