# Generated by Django 5.1.7 on 2025-08-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkProgress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workprogress',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='Porcentaje de avance'),
        ),
    ]
