# Generated by Django 5.1.7 on 2025-09-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Option', '0005_alter_option_name'),
        ('WorkOrder', '0006_remove_workorder_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Option.option')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WorkOrder.workorder')),
            ],
        ),
    ]
