# Generated by Django 5.1.7 on 2025-07-07 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Egress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=250, verbose_name='responsabel del movimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto de dinero')),
                ('date', models.DateField(verbose_name='fecha')),
                ('reason', models.CharField(max_length=250, verbose_name='motivo')),
                ('payment_method', models.CharField(max_length=250, verbose_name='metodo de pago')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('voucher', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comprobante')),
                ('origin_account', models.IntegerField(choices=[(1, 'CUENTA BANCARIA'), (2, 'CAJA PRINCIPAL')], verbose_name='cuenta de origen')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(max_length=250, verbose_name='responsabel del movimiento')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto de dinero')),
                ('date', models.DateField(verbose_name='fecha')),
                ('reason', models.CharField(max_length=250, verbose_name='motivo')),
                ('payment_method', models.CharField(max_length=250, verbose_name='metodo de pago')),
                ('observations', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('voucher', models.CharField(blank=True, max_length=250, null=True, verbose_name='Comprobante')),
                ('destination_account', models.IntegerField(choices=[(1, 'CUENTA BANCARIA'), (2, 'CAJA PRINCIPAL')], verbose_name='cuenta destino')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
