# Generated by Django 5.1.7 on 2025-07-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_movement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egress',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='egress',
            name='voucher',
            field=models.CharField(blank=True, max_length=250, verbose_name='Comprobante'),
        ),
        migrations.AlterField(
            model_name='income',
            name='observations',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='income',
            name='voucher',
            field=models.CharField(blank=True, max_length=250, verbose_name='Comprobante'),
        ),
    ]
