# Generated by Django 5.1.7 on 2025-09-08 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Financial_movement', '0002_alter_egress_observations_alter_egress_voucher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Banco'), (2, 'Caja')], verbose_name='tipo de cuenta')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monto inicial')),
                ('name', models.CharField(max_length=100, verbose_name='nombre de la cuenta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='egress',
            options={'ordering': ['-date'], 'verbose_name': 'Egreso', 'verbose_name_plural': 'Egresos'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date'], 'verbose_name': 'Ingreso', 'verbose_name_plural': 'Ingresos'},
        ),
        migrations.AlterField(
            model_name='egress',
            name='origin_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='egresses', to='Financial_movement.account', verbose_name='cuenta de origen'),
        ),
        migrations.AlterField(
            model_name='income',
            name='destination_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='Financial_movement.account', verbose_name='cuenta destino'),
        ),
    ]
