# Generated by Django 5.1.7 on 2025-04-12 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=600, null=True)),
                ('code', models.CharField(max_length=200, null=True, unique=True)),
                ('state', models.IntegerField(choices=[(1, 'Activa'), (2, 'Inactiva'), (3, 'En uso'), (4, 'Reservada')], default=1)),
                ('image', models.CharField(max_length=500)),
                ('marca', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
