# Generated by Django 5.1.7 on 2025-06-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='state',
            field=models.IntegerField(choices=[(1, 'Activa'), (2, 'Inactiva'), (3, 'En uso'), (4, 'Reservada')], default=1),
        ),
    ]
