# Generated by Django 5.1.7 on 2025-06-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
