# Generated by Django 5.1.7 on 2025-06-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_tool_code'),
        ('tool', '0002_alter_tool_code_alter_tool_state'),
    ]

    operations = [
    ]
