# Generated by Django 5.1.7 on 2025-09-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_merge_20250629_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='state',
            field=models.IntegerField(choices=[(1, 'Activa'), (2, 'Inactiva'), (3, 'En uso'), (4, 'Reservada'), (5, 'En mantenimiento')], default=1),
        ),
    ]
