# Generated by Django 5.1.7 on 2025-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Description')),
                ('units', models.IntegerField(verbose_name='Units')),
                ('amount', models.IntegerField(verbose_name='Amount')),
                ('unit_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Unit Value')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Value')),
            ],
        ),
    ]
