# Generated by Django 5.1.7 on 2025-06-26 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_item_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='total_value',
        ),
    ]
