# Generated by Django 5.1.7 on 2025-07-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exhibit', '0002_remove_exhibit_image_exhibit_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('exhibits', models.ManyToManyField(blank=True, to='exhibit.exhibit', verbose_name='Exhibits')),
            ],
        ),
    ]
