# Generated by Django 5.1.7 on 2025-06-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Value')),
                ('items', models.ManyToManyField(related_name='options', to='item.item', verbose_name='Items')),
            ],
        ),
    ]
