# Generated by Django 5.1.7 on 2025-06-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Option', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='option',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True, verbose_name='Total Value'),
        ),
    ]
