# Generated by Django 5.1.7 on 2025-06-26 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Option', '0002_option_subtotal_alter_option_total_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='subtotal',
        ),
    ]
