# Generated by Django 5.1.7 on 2025-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Option', '0004_remove_option_total_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Name'),
        ),
    ]
