# Generated by Django 5.1.7 on 2025-09-04 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tool', '0004_alter_tool_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_technician_name', models.CharField(max_length=700)),
                ('date', models.DateField(auto_now_add=True)),
                ('maintenance_days', models.IntegerField()),
                ('observations', models.TextField(blank=True)),
                ('next_maintenance_date', models.DateField()),
                ('tool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tool.tool')),
            ],
        ),
    ]
