# Generated by Django 5.1.7 on 2025-09-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='type',
            field=models.IntegerField(choices=[(1, 'Correctivo'), (2, 'preventivo')], default=1),
        ),
    ]
