# Generated by Django 5.1.7 on 2025-09-05 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0002_maintenance_type'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='user_delivery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
