# Generated by Django 5.1.7 on 2025-09-09 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maintenance', '0003_maintenance_user_delivery'),
        ('tool', '0004_alter_tool_state'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='tool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.tool'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='user_delivery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
