# Generated by Django 5.1.7 on 2025-06-03 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Quotes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('Quotes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Quotes.quotes', verbose_name='Quote')),
            ],
        ),
    ]
