# Generated by Django 5.1.7 on 2025-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='activity',
            field=models.IntegerField(blank=True, choices=[(1, 'Emergencia'), (2, 'Programado')], null=True, verbose_name='Activity Type'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='number_auxiliaries',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Auxiliaries'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='number_officers',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Officers'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='number_technicians',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of Technicians'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='permissions',
            field=models.JSONField(blank=True, null=True, verbose_name='Activity Permissions'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='workplace',
            field=models.IntegerField(blank=True, choices=[(1, 'Instalaciones Propias'), (2, 'Instalaciones del Cliente')], null=True, verbose_name='Workplace Type'),
        ),
    ]
