# Generated by Django 5.1.7 on 2025-06-19 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrder', '0002_workorder_activity_workorder_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workorder',
            old_name='Quotes',
            new_name='quote',
        ),
    ]
