# Generated by Django 5.1.7 on 2025-07-05 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrder', '0004_workorder_number_supervisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='descriptions'),
        ),
    ]
