# Generated by Django 5.1.7 on 2025-07-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WorkOrder', '0005_alter_workorder_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='end_date',
        ),
        migrations.AddField(
            model_name='workorder',
            name='days_of_execution',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days of Execution'),
        ),
    ]
