# Generated by Django 5.1.7 on 2025-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exhibit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='image',
        ),
        migrations.AddField(
            model_name='exhibit',
            name='images',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Image'),
        ),
    ]
