# Generated by Django 5.1.7 on 2025-06-18 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('WorkOrder', '0001_initial'),
        ('exhibit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('observations', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendations', models.CharField(blank=True, max_length=255, null=True)),
                ('exhibit', models.ManyToManyField(blank=True, related_name='delivery_certificates', to='exhibit.exhibit')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_certificates', to='WorkOrder.workorder')),
            ],
        ),
    ]
