# Generated by Django 5.1.7 on 2025-06-19 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_certificate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_certificate',
            name='description',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='delivery_certificate',
            name='development',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
