# Generated by Django 5.1.7 on 2025-07-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Delivery_certificate', '0002_delivery_certificate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_certificate',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='delivery_certificate',
            name='development',
            field=models.TextField(blank=True, null=True, verbose_name='development'),
        ),
        migrations.AlterField(
            model_name='delivery_certificate',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='observations'),
        ),
        migrations.AlterField(
            model_name='delivery_certificate',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='recommendations'),
        ),
    ]
