# Generated by Django 5.1.7 on 2025-07-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_post_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='representative',
            field=models.CharField(default=' ', max_length=200, verbose_name='representative'),
        ),
    ]
