# Generated by Django 5.1.7 on 2025-07-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=15, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='post',
            field=models.CharField(blank=True, max_length=100, verbose_name='Post'),
        ),
    ]
